name: Build & Release

on:
  repository_dispatch:
    types:
      - build-web 

jobs:
  build-project:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Get App Icon
        run:  wget ${{ github.event.client_payload.appIconUrl }} -O ./assets/app_icon/main.png
      
      - name: Check App Icon
        run: ls -l ./assets/app_icon/
      

      # - name: Set up Flutter
      #   uses: subosito/flutter-action@v2
      #   with:
      #     channel: stable
      #     flutter-version: '3.24.3'

      # - run: flutter --version

      # - name: Install GitHub CLI
      #   run: sudo apt-get install gh -y

      # - name: Install dependencies
      #   run: flutter pub get

      # - name: Build Flutter Web
      #   run: flutter build web --release --no-tree-shake-icons


      # - name: Upload Build Files
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: web
      #     path: ./build/web

  # release-build-files:
  #   name: Publish Build Files
  #   runs-on: ubuntu-latest
  #   needs: build-project
  #   steps:
  #   - name: Download Build Files
  #     uses: actions/download-artifact@v4
  #     with:
  #       name: web
    
  #   - name: Test Download Files
  #     run: ls -R

  #   - name: Archive Downloaded Files
  #     uses: thedoctor0/zip-release@0.7.5
  #     with:
  #       filename: web.zip

  #   - name: Create Github Release
  #     id: create-github-release
  #     uses: actions/create-release@v1
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     with:
  #       tag_name: ${{ github.run_number }}
  #       release_name: Release ${{ github.run_number }}

  #   - name: Upload Release Assets
  #     uses: actions/upload-release-asset@v1
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     with:
  #       upload_url: ${{ steps.create-github-release.outputs.upload_url }}
  #       asset_path: ./web.zip
  #       asset_name: acnoo_flutter_admin_panel_web_v${{ github.run_number }}.zip
  #       asset_content_type: application/zip
