name: Build & Release

on:
  repository_dispatch:
    types:
      - build-web 

jobs:
  build-project:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Get Custom App Icon
        if: ${{ github.event.client_payload.appIconUrl != null }}
        run:  wget ${{ github.event.client_payload.appIconUrl }} -O assets/app_icon/main.png
      
      - name: Check App Icon
        run: ls -l assets/app_icon/
      

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.24.3'

      - run: |
          flutter --version
          java --version
          javac --version

      # - name: Install GitHub CLI
      #   run: sudo apt-get install gh -y

      # - name: Install dependencies
      #   run: flutter pub get
      
      # - name: Change App Icon
      #   run: dart run icons_launcher:create --path=icon_config.yaml
      
      # - name: Change App Name
      #   if: ${{ github.event.client_payload.appName != null }}
      #   run: dart run rename_app:main all=${{ github.event.client_payload.appName }}

      # - name: Change Package Name
      #   if: ${{ github.event.client_payload.packageName != null }}
      #   run: dart run change_app_package_name:main ${{ github.event.client_payload.packageName }}

      # # - name: Build Flutter Web
      # #   run: flutter build web --release --no-tree-shake-icons
      # - name: Build Android APK
      #   run: |
      #     flutter clean
      #     flutter build apk


      # - name: Upload Build Files
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: build-files
      #     path: |
      #       ./build/app/outputs/flutter-apk/
